/**
 * Typed anatomical region data for the BodyViewer.
 *
 * The heavy table itself is generated by `scripts/build_body_asset.py`
 * (it derives focus targets, radii and neighbour graphs directly from the
 * segmented mesh) — this module is the stable import surface.
 */
export type { BodyRegion } from './types';
export { REGIONS, REGION_BY_ID, REGION_BY_NUMERIC } from './regions.gen';

import { REGIONS } from './regions.gen';
import type { BodyGroup, Locale } from './types';

export const GROUP_LABELS: Record<BodyGroup, { en: string; ar: string }> = {
  head_neck: { en: 'Head & Neck', ar: 'الرأس والعنق' },
  shoulder_arm: { en: 'Shoulder & Arm', ar: 'الكتف والذراع' },
  trunk: { en: 'Trunk', ar: 'الجذع' },
  lower_limb: { en: 'Lower Limb', ar: 'الطرف السفلي' },
};

export function regionLabel(id: string, locale: Locale): string {
  const r = REGIONS.find((x) => x.id === id);
  if (!r) return id;
  return locale === 'ar' && r.labelAr ? r.labelAr : r.label;
}
