// AUTO-GENERATED by scripts/content-build.ts — do not edit by hand.
// Source: content/*.csv  ·  Generated: 2026-09-06
// To change any of this, edit the spreadsheets and run: npm run content:build
import type { ContentBundle } from './types';

export const CONTENT: ContentBundle = {
  "bodyAreas": [
    {
      "id": "lower_back",
      "label": {
        "en": "Lower Back",
        "ar": "أسفل الظهر"
      },
      "regionIds": [
        "lumbar_spine",
        "sacrum_si",
        "left_oblique",
        "right_oblique"
      ]
    },
    {
      "id": "neck",
      "label": {
        "en": "Neck",
        "ar": "الرقبة"
      },
      "regionIds": [
        "cervical_upper",
        "cervical_lower",
        "throat",
        "left_trapezius",
        "right_trapezius"
      ]
    }
  ],
  "questions": [
    {
      "id": "lb_q1",
      "bodyArea": "lower_back",
      "key": "movement",
      "prompt": {
        "en": "Which movement feels most limited or uncomfortable?",
        "ar": "ما الحركة التي تشعر أنها الأكثر تقييداً أو إزعاجاً؟"
      },
      "hint": {
        "en": "Pick the closest one. You can skip this.",
        "ar": "اختر الأقرب. يمكنك تخطي هذا السؤال."
      },
      "options": [
        {
          "id": "lb_q1_a",
          "key": "bending_forward",
          "label": {
            "en": "Bending forward",
            "ar": "الانحناء للأمام"
          }
        },
        {
          "id": "lb_q1_b",
          "key": "leaning_back",
          "label": {
            "en": "Leaning backward",
            "ar": "الميل للخلف"
          }
        },
        {
          "id": "lb_q1_c",
          "key": "twisting",
          "label": {
            "en": "Twisting side to side",
            "ar": "الالتفاف يميناً ويساراً"
          }
        },
        {
          "id": "lb_q1_d",
          "key": "numbness_weakness",
          "label": {
            "en": "I have numbness, tingling or weakness in a leg",
            "ar": "أشعر بخدر أو تنميل أو ضعف في الساق"
          },
          "redFlag": true,
          "escalationId": "esc_see_someone"
        }
      ],
      "order": 1,
      "skippable": true,
      "status": "published",
      "reviewedBy": "PLACEHOLDER",
      "reviewedOn": "2026-09-06"
    },
    {
      "id": "g_onset",
      "bodyArea": "global",
      "key": "onset",
      "prompt": {
        "en": "Did this start after a particular activity, or has it been around for a while?",
        "ar": "هل بدأ هذا بعد نشاط معيّن، أم أنه موجود منذ فترة؟"
      },
      "options": [
        {
          "id": "g_onset_a",
          "key": "new_after_activity",
          "label": {
            "en": "New, after an activity",
            "ar": "جديد، بعد نشاط"
          }
        },
        {
          "id": "g_onset_b",
          "key": "long_standing",
          "label": {
            "en": "It has been around for a while",
            "ar": "موجود منذ فترة"
          }
        }
      ],
      "order": 1,
      "skippable": false,
      "status": "published",
      "reviewedBy": "PLACEHOLDER",
      "reviewedOn": "2026-09-06"
    },
    {
      "id": "g_duration",
      "bodyArea": "global",
      "key": "duration",
      "prompt": {
        "en": "Roughly how long has it been present?",
        "ar": "منذ متى تقريباً وهو موجود؟"
      },
      "options": [
        {
          "id": "g_dur_a",
          "key": "days",
          "label": {
            "en": "A few days",
            "ar": "بضعة أيام"
          }
        },
        {
          "id": "g_dur_b",
          "key": "weeks",
          "label": {
            "en": "A few weeks",
            "ar": "بضعة أسابيع"
          }
        },
        {
          "id": "g_dur_c",
          "key": "months",
          "label": {
            "en": "Months or longer",
            "ar": "أشهر أو أكثر"
          }
        }
      ],
      "order": 2,
      "skippable": true,
      "status": "published",
      "reviewedBy": "PLACEHOLDER",
      "reviewedOn": "2026-09-06"
    },
    {
      "id": "g_irritability",
      "bodyArea": "global",
      "key": "irritability",
      "prompt": {
        "en": "If it gets stirred up, how long before it settles?",
        "ar": "إذا اشتد، كم يمضي قبل أن يهدأ؟"
      },
      "options": [
        {
          "id": "g_irr_a",
          "key": "quick",
          "label": {
            "en": "It settles quickly",
            "ar": "يهدأ بسرعة"
          }
        },
        {
          "id": "g_irr_b",
          "key": "hours",
          "label": {
            "en": "An hour or two",
            "ar": "ساعة أو ساعتان"
          }
        },
        {
          "id": "g_irr_c",
          "key": "day",
          "label": {
            "en": "The rest of the day",
            "ar": "بقية اليوم"
          }
        }
      ],
      "order": 3,
      "skippable": false,
      "status": "published",
      "reviewedBy": "PLACEHOLDER",
      "reviewedOn": "2026-09-06"
    },
    {
      "id": "g_pattern",
      "bodyArea": "global",
      "key": "pattern",
      "prompt": {
        "en": "When in the day does it tend to bother you most?",
        "ar": "في أي وقت من اليوم يزعجك أكثر؟"
      },
      "options": [
        {
          "id": "g_pat_a",
          "key": "morning",
          "label": {
            "en": "Worse in the morning",
            "ar": "أسوأ في الصباح"
          }
        },
        {
          "id": "g_pat_b",
          "key": "sitting",
          "label": {
            "en": "Worse with sitting",
            "ar": "أسوأ مع الجلوس"
          }
        },
        {
          "id": "g_pat_c",
          "key": "activity",
          "label": {
            "en": "Worse with activity",
            "ar": "أسوأ مع النشاط"
          }
        }
      ],
      "order": 4,
      "skippable": true,
      "status": "published",
      "reviewedBy": "PLACEHOLDER",
      "reviewedOn": "2026-09-06"
    },
    {
      "id": "lb_q2",
      "bodyArea": "lower_back",
      "key": "timing",
      "prompt": {
        "en": "When does it bother you most?",
        "ar": "متى يزعجك أكثر؟"
      },
      "options": [
        {
          "id": "lb_q2_a",
          "key": "mornings",
          "label": {
            "en": "In the morning",
            "ar": "في الصباح"
          }
        },
        {
          "id": "lb_q2_b",
          "key": "after_sitting",
          "label": {
            "en": "After sitting a long time",
            "ar": "بعد الجلوس لفترة طويلة"
          }
        },
        {
          "id": "lb_q2_c",
          "key": "during_activity",
          "label": {
            "en": "During or after activity",
            "ar": "أثناء النشاط أو بعده"
          }
        },
        {
          "id": "lb_q2_d",
          "key": "night_pain",
          "label": {
            "en": "At night — it wakes me up",
            "ar": "في الليل — يوقظني من النوم"
          },
          "redFlag": true,
          "escalationId": "esc_see_someone"
        }
      ],
      "order": 2,
      "skippable": true,
      "status": "published",
      "reviewedBy": "PLACEHOLDER",
      "reviewedOn": "2026-09-06"
    }
  ],
  "routes": [
    {
      "id": "lb_r1",
      "bodyArea": "lower_back",
      "answerPath": "movement=bending_forward&timing=mornings",
      "outcome": "exercises",
      "exerciseIds": [
        "lb_ex_pelvic_tilt",
        "lb_ex_cat_camel"
      ],
      "status": "published",
      "reviewedBy": "PLACEHOLDER",
      "reviewedOn": "2026-09-06"
    },
    {
      "id": "lb_r2",
      "bodyArea": "lower_back",
      "answerPath": "movement=bending_forward&timing=after_sitting",
      "outcome": "exercises",
      "exerciseIds": [
        "lb_ex_cat_camel",
        "lb_ex_sit_stand",
        "lb_ex_knee_to_chest"
      ],
      "status": "published",
      "reviewedBy": "PLACEHOLDER",
      "reviewedOn": "2026-09-06"
    },
    {
      "id": "lb_r3",
      "bodyArea": "lower_back",
      "answerPath": "movement=leaning_back&timing=after_sitting",
      "outcome": "exercises",
      "exerciseIds": [
        "lb_ex_knee_to_chest",
        "lb_ex_pelvic_tilt"
      ],
      "status": "published",
      "reviewedBy": "PLACEHOLDER",
      "reviewedOn": "2026-09-06"
    },
    {
      "id": "lb_r4",
      "bodyArea": "lower_back",
      "answerPath": "movement=twisting&timing=during_activity",
      "outcome": "exercises",
      "exerciseIds": [
        "lb_ex_cat_camel",
        "lb_ex_pelvic_tilt"
      ],
      "status": "published",
      "reviewedBy": "PLACEHOLDER",
      "reviewedOn": "2026-09-06"
    }
  ],
  "exercises": [
    {
      "id": "lb_ex_pelvic_tilt",
      "bodyArea": "lower_back",
      "name": {
        "en": "Pelvic Tilt",
        "ar": "إمالة الحوض"
      },
      "purpose": {
        "en": "A gentle way to start moving the lower back through a small, controlled range.",
        "ar": "طريقة لطيفة لبدء تحريك أسفل الظهر ضمن مدى صغير ومضبوط."
      },
      "dosage": {
        "en": "10 repetitions, hold 5 seconds. Twice a day.",
        "ar": "١٠ تكرارات، ثبات ٥ ثوانٍ. مرتين يومياً."
      },
      "safety": {
        "en": "Stop if this increases your pain or causes symptoms down your leg.",
        "ar": "توقف إذا زاد هذا من ألمك أو سبب أعراضاً في ساقك."
      },
      "steps": [
        {
          "en": "Lie on your back with your knees bent and feet flat on the floor.",
          "ar": "استلقِ على ظهرك مع ثني الركبتين ووضع القدمين على الأرض."
        },
        {
          "en": "Gently flatten your lower back towards the floor.",
          "ar": "اضغط أسفل ظهرك برفق نحو الأرض."
        },
        {
          "en": "Hold, then release back to a comfortable resting position.",
          "ar": "اثبت، ثم عد إلى وضع الراحة المريح."
        }
      ],
      "status": "published",
      "reviewedBy": "PLACEHOLDER",
      "reviewedOn": "2026-09-06"
    },
    {
      "id": "lb_ex_knee_to_chest",
      "bodyArea": "lower_back",
      "name": {
        "en": "Single Knee to Chest",
        "ar": "سحب الركبة إلى الصدر"
      },
      "purpose": {
        "en": "Eases the lower back into flexion one side at a time.",
        "ar": "يساعد أسفل الظهر على الانثناء تدريجياً جانباً واحداً في كل مرة."
      },
      "dosage": {
        "en": "Hold 20 seconds, 3 times each side. Once a day.",
        "ar": "ثبات ٢٠ ثانية، ٣ مرات لكل جانب. مرة يومياً."
      },
      "safety": {
        "en": "Keep the movement slow. Do not pull into pain.",
        "ar": "حافظ على بطء الحركة. لا تسحب إلى حد الألم."
      },
      "steps": [
        {
          "en": "Lie on your back with both knees bent.",
          "ar": "استلقِ على ظهرك مع ثني الركبتين."
        },
        {
          "en": "Draw one knee gently towards your chest with both hands.",
          "ar": "اسحب إحدى الركبتين برفق نحو صدرك بكلتا اليدين."
        },
        {
          "en": "Hold, lower slowly, then repeat on the other side.",
          "ar": "اثبت، ثم أنزلها ببطء وكرر مع الجانب الآخر."
        }
      ],
      "status": "published",
      "reviewedBy": "PLACEHOLDER",
      "reviewedOn": "2026-09-06"
    },
    {
      "id": "lb_ex_cat_camel",
      "bodyArea": "lower_back",
      "name": {
        "en": "Cat–Camel",
        "ar": "تمرين القطة والجمل"
      },
      "purpose": {
        "en": "Moves the whole spine through its range without loading it.",
        "ar": "يحرك العمود الفقري بالكامل ضمن مداه دون تحميل عليه."
      },
      "dosage": {
        "en": "10 slow cycles. Twice a day.",
        "ar": "١٠ دورات بطيئة. مرتين يومياً."
      },
      "safety": {
        "en": "Move only as far as is comfortable in each direction.",
        "ar": "تحرك فقط ضمن المدى المريح في كل اتجاه."
      },
      "steps": [
        {
          "en": "Start on your hands and knees.",
          "ar": "ابدأ على يديك وركبتيك."
        },
        {
          "en": "Slowly round your back upwards.",
          "ar": "قوّس ظهرك ببطء إلى الأعلى."
        },
        {
          "en": "Then slowly let it sag downwards. Move smoothly between the two.",
          "ar": "ثم أنزله ببطء إلى الأسفل. تحرك بسلاسة بين الوضعين."
        }
      ],
      "suitsAgeBands": [
        "teen",
        "adult",
        "older_adult"
      ],
      "status": "published",
      "reviewedBy": "PLACEHOLDER",
      "reviewedOn": "2026-09-06"
    },
    {
      "id": "lb_ex_sit_stand",
      "bodyArea": "lower_back",
      "name": {
        "en": "Sit to Stand",
        "ar": "الجلوس والوقوف"
      },
      "purpose": {
        "en": "Builds confidence with the movement most used in daily life.",
        "ar": "يبني الثقة بالحركة الأكثر استخداماً في الحياة اليومية."
      },
      "dosage": {
        "en": "8 repetitions. Twice a day.",
        "ar": "٨ تكرارات. مرتين يومياً."
      },
      "safety": {
        "en": "Have a stable surface nearby to hold if you feel unsteady.",
        "ar": "احرص على وجود سطح ثابت قريب للإمساك به إذا شعرت بعدم الاتزان."
      },
      "steps": [
        {
          "en": "Sit towards the front of a stable chair.",
          "ar": "اجلس نحو مقدمة كرسي ثابت."
        },
        {
          "en": "Stand up without using your hands if you can.",
          "ar": "قف دون استخدام يديك إن أمكن."
        },
        {
          "en": "Sit back down slowly and with control.",
          "ar": "اجلس ببطء وتحكم."
        }
      ],
      "status": "published",
      "reviewedBy": "PLACEHOLDER",
      "reviewedOn": "2026-09-06"
    }
  ],
  "escalations": [
    {
      "id": "esc_see_someone",
      "title": {
        "en": "Let’s have someone look at this first",
        "ar": "دعنا نجعل أحد المختصين يفحص هذا أولاً"
      },
      "body": {
        "en": "What you described is something a physiotherapist should assess in person before you start any exercises. This is not a cause for alarm — it simply means exercises are not the right next step until someone has examined you. Please get in touch and we will arrange an appointment.",
        "ar": "ما وصفته يحتاج إلى تقييم مباشر من أخصائي علاج طبيعي قبل البدء بأي تمارين. هذا ليس داعياً للقلق، لكنه يعني ببساطة أن التمارين ليست الخطوة التالية المناسبة قبل الفحص. يرجى التواصل معنا لتحديد موعد."
      },
      "cta": "contact",
      "status": "published",
      "reviewedBy": "PLACEHOLDER",
      "reviewedOn": "2026-09-06"
    }
  ],
  "redFlags": [
    {
      "id": "rf_trauma",
      "prompt": {
        "en": "Did this start after a fall, a collision, or another significant impact?",
        "ar": "هل بدأ هذا بعد سقوط أو اصطدام أو تأثير قوي؟"
      },
      "positiveKey": "yes",
      "messageId": "esc_see_someone",
      "order": 1,
      "status": "published",
      "reviewedBy": "PLACEHOLDER",
      "reviewedOn": "2026-09-06"
    },
    {
      "id": "rf_neuro",
      "prompt": {
        "en": "Are you noticing new numbness, tingling that is spreading, or weakness in an arm or a leg?",
        "ar": "هل تلاحظ خدراً جديداً أو تنميلاً منتشراً أو ضعفاً في ذراع أو ساق؟"
      },
      "positiveKey": "yes",
      "messageId": "esc_see_someone",
      "order": 2,
      "status": "published",
      "reviewedBy": "PLACEHOLDER",
      "reviewedOn": "2026-09-06"
    },
    {
      "id": "rf_night",
      "prompt": {
        "en": "Does pain wake you at night and stay with you even after you change position?",
        "ar": "هل يوقظك الألم ليلاً ويبقى حتى بعد تغيير وضعيتك؟"
      },
      "positiveKey": "yes",
      "messageId": "esc_see_someone",
      "order": 3,
      "status": "published",
      "reviewedBy": "PLACEHOLDER",
      "reviewedOn": "2026-09-06"
    },
    {
      "id": "rf_bladder",
      "prompt": {
        "en": "Have you noticed a change in bladder or bowel control that is new for you?",
        "ar": "هل لاحظت تغيراً جديداً في التحكم بالمثانة أو الأمعاء؟"
      },
      "positiveKey": "yes",
      "messageId": "esc_see_someone",
      "order": 4,
      "status": "published",
      "reviewedBy": "PLACEHOLDER",
      "reviewedOn": "2026-09-06"
    },
    {
      "id": "rf_weight",
      "prompt": {
        "en": "Have you lost weight without trying, alongside this pain?",
        "ar": "هل فقدت وزناً دون محاولة، مع هذا الألم؟"
      },
      "positiveKey": "yes",
      "messageId": "esc_see_someone",
      "order": 5,
      "status": "published",
      "reviewedBy": "PLACEHOLDER",
      "reviewedOn": "2026-09-06"
    },
    {
      "id": "rf_chest",
      "prompt": {
        "en": "Do you get chest tightness, unusual breathlessness, or arm pain with effort?",
        "ar": "هل تشعر بضيق في الصدر أو ضيق نفس غير معتاد أو ألم في الذراع مع الجهد؟"
      },
      "positiveKey": "yes",
      "messageId": "esc_see_someone",
      "order": 6,
      "status": "published",
      "reviewedBy": "PLACEHOLDER",
      "reviewedOn": "2026-09-06"
    }
  ],
  "precautions": [
    {
      "conditionKey": "none",
      "label": {
        "en": "None of these",
        "ar": "لا شيء من هذا"
      },
      "restrictsTags": [],
      "restrictsIds": [],
      "action": "warn",
      "messageId": "esc_see_someone",
      "status": "published",
      "reviewedBy": "PLACEHOLDER",
      "reviewedOn": "2026-09-06"
    },
    {
      "conditionKey": "prefer_not_to_say",
      "label": {
        "en": "Prefer not to say",
        "ar": "أفضل عدم الإفصاح"
      },
      "restrictsTags": [],
      "restrictsIds": [],
      "action": "warn",
      "messageId": "esc_see_someone",
      "status": "published",
      "reviewedBy": "PLACEHOLDER",
      "reviewedOn": "2026-09-06"
    },
    {
      "conditionKey": "recent_surgery",
      "label": {
        "en": "Recent surgery in the last 3 months",
        "ar": "عملية جراحية خلال الأشهر الثلاثة الماضية"
      },
      "restrictsTags": [],
      "restrictsIds": [],
      "action": "stop_and_refer",
      "messageId": "esc_see_someone",
      "status": "published",
      "reviewedBy": "PLACEHOLDER",
      "reviewedOn": "2026-09-06"
    },
    {
      "conditionKey": "balance_concern",
      "label": {
        "en": "A balance problem that makes standing unaided unsafe",
        "ar": "مشكلة في التوازن تجعل الوقوف دون مساعدة غير آمن"
      },
      "restrictsTags": [],
      "restrictsIds": [
        "lb_ex_sit_stand"
      ],
      "action": "hide",
      "messageId": "esc_see_someone",
      "status": "published",
      "reviewedBy": "PLACEHOLDER",
      "reviewedOn": "2026-09-06"
    },
    {
      "conditionKey": "pregnancy_or_postpartum",
      "label": {
        "en": "Currently pregnant or within 6 weeks after birth",
        "ar": "حامل حالياً أو خلال ستة أسابيع بعد الولادة"
      },
      "restrictsTags": [],
      "restrictsIds": [],
      "action": "stop_and_refer",
      "messageId": "esc_see_someone",
      "status": "published",
      "reviewedBy": "PLACEHOLDER",
      "reviewedOn": "2026-09-06"
    }
  ],
  "thresholds": [
    {
      "key": "nrs_referral",
      "value": 8,
      "status": "published",
      "reviewedBy": "PLACEHOLDER",
      "reviewedOn": "2026-09-06"
    },
    {
      "key": "amber_window_hours",
      "value": 24,
      "status": "published",
      "reviewedBy": "PLACEHOLDER",
      "reviewedOn": "2026-09-06"
    },
    {
      "key": "rising_sessions_n",
      "value": 3,
      "status": "published",
      "reviewedBy": "PLACEHOLDER",
      "reviewedOn": "2026-09-06"
    },
    {
      "key": "review_weeks",
      "value": 6,
      "status": "published",
      "reviewedBy": "PLACEHOLDER",
      "reviewedOn": "2026-09-06"
    },
    {
      "key": "reminder_days",
      "value": 21,
      "status": "published",
      "reviewedBy": "PLACEHOLDER",
      "reviewedOn": "2026-09-06"
    }
  ]
};
