/**
 * Compile content/*.csv -> src/content/bundle.gen.ts
 *
 * This is what makes the sheet the source of truth: the clinician edits a
 * spreadsheet, runs `npm run content:build`, and the app changes. No code.
 *
 * Refuses to emit anything if validation fails, so a broken sheet can never
 * reach a patient in a degraded state.
 */
import { readFileSync, existsSync, writeFileSync } from 'node:fs';
import { validateContent, formatIssues, type SourceFiles } from '../src/content/validate';
import { selectPublished } from '../src/content/routing';

const NAMES: Array<keyof SourceFiles> = [
  'body_areas.csv',
  'questions.csv',
  'answer_options.csv',
  'escalation_messages.csv',
  'exercises.csv',
  'routes.csv',
  'red_flags.csv',
  'precautions.csv',
  'thresholds.csv',
];

const OUT = 'src/content/bundle.gen.ts';

if (NAMES.some((n) => !existsSync(`content/${n}`))) {
  console.error('Missing content sheets. Run `npm run content:export` first.');
  process.exit(1);
}

const files = Object.fromEntries(
  NAMES.map((n) => [n, readFileSync(`content/${n}`, 'utf8')]),
) as SourceFiles;

const { bundle, issues, ok } = validateContent(files);
const errs = issues.filter((i) => i.severity === 'error');
const warns = issues.filter((i) => i.severity === 'warning');

if (!ok) {
  console.error(formatIssues(errs));
  console.error('\n✖ Not writing bundle — fix the errors above first.');
  process.exit(1);
}

if (warns.length) console.warn(formatIssues(warns));

const header = `// AUTO-GENERATED by scripts/content-build.ts — do not edit by hand.
// Source: content/*.csv  ·  Generated: ${new Date().toISOString().slice(0, 10)}
// To change any of this, edit the spreadsheets and run: npm run content:build
import type { ContentBundle } from './types';

export const CONTENT: ContentBundle = `;

writeFileSync(OUT, header + JSON.stringify(bundle, null, 2) + ';\n', 'utf8');

const pub = selectPublished(bundle.exercises);
console.log(`✅ Wrote ${OUT}`);
console.log(`   ${bundle.bodyAreas.length} area(s), ${pub.length} published exercise(s), ${selectPublished(bundle.questions).length} published question(s)`);
